# Authour: Bill Van Leeuwen
# Purpose: Get Gitlab image, configure and start it

- name: Gitlab
  hosts: all
  become_user: root
  become: true
  vars:
    gitlab_home: "/srv/gitlab"
  vars_prompt: 
  - name: domain
    prompt: Enter your planned url for your gitlab instance.
  tasks:

  - name: Create the volume directories
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
      mode: '0755'
      owner: root
    loop: 
      - "{{gitlab_home}}/config"
      - "{{gitlab_home}}/logs"
      - "{{gitlab_home}}/data"

  - name: Set gitlab configurations file.
    ansible.builtin.blockinfile:
      path: "{{gitlab_home}}/config/gitlab.rb"
      block: | 
        external_url '{{domain}}'
      #TODO: can configure Gitlab root password here with ansible vault
      create: yes

  - name: Get and run gitlab image
    containers.podman.podman_container:
      name: gitlab
      image: docker.io/gitlab/gitlab-ce:latest
      restart: yes
      shm_size: 256m
      publish: 
      - 80:80 
      - 443:443
      - 1022:22
      volume: 
        - "{{gitlab_home}}/config:/etc/gitlab:Z"
        - "{{gitlab_home}}/logs:/var/log/gitlab:Z"
        - "{{gitlab_home}}/data:/var/opt/gitlab:Z"
  
      state: started